"""
Run this once to write two files directly -- the new ProductRecord
model and the updated main.py that registers persistence and the
fixed /products route. Delete this file afterwards if you like.
"""

models_content = 'from datetime import datetime, timezone\n\nfrom sqlalchemy import String, Float, Integer, DateTime\nfrom sqlalchemy.orm import Mapped, mapped_column\n\nfrom app.database.base import Base\n\n\nclass ProductRecord(Base):\n    """\n    A saved snapshot of one opportunity from a scan -- one row per\n    (ASIN, scan run). This is what lets the Products page show\n    history across restarts without re-querying Keepa, and gives you\n    a record of what a product looked like when you saw it, even if\n    the numbers change later.\n\n    NOTE: this only saves opportunities that made it into a scan\'s\n    results list (i.e. had a real UK price and a real EU source) --\n    excluded/filtered-out products are not persisted.\n    """\n    __tablename__ = "product_records"\n\n    id: Mapped[int] = mapped_column(Integer, primary_key=True)\n\n    asin: Mapped[str] = mapped_column(String, index=True)\n    title: Mapped[str] = mapped_column(String, default="")\n    brand: Mapped[str] = mapped_column(String, default="")\n    category: Mapped[str] = mapped_column(String, default="")\n\n    # What brand search produced this record, e.g. "philips"\n    brand_query: Mapped[str] = mapped_column(String, default="")\n\n    buy_box_now: Mapped[float] = mapped_column(Float, default=0.0)\n    buy_box_90d: Mapped[float] = mapped_column(Float, default=0.0)\n\n    best_source_marketplace: Mapped[str] = mapped_column(String, default="")\n    best_source_cost_gbp: Mapped[float] = mapped_column(Float, default=0.0)\n\n    fba_fee: Mapped[float] = mapped_column(Float, default=0.0)\n    referral_fee: Mapped[float] = mapped_column(Float, default=0.0)\n    profit: Mapped[float] = mapped_column(Float, default=0.0)\n    roi: Mapped[float] = mapped_column(Float, default=0.0)\n\n    score: Mapped[int] = mapped_column(Integer, default=0)\n    confidence: Mapped[int] = mapped_column(Integer, default=0)\n    recommendation: Mapped[str] = mapped_column(String, default="")\n\n    scanned_at: Mapped[datetime] = mapped_column(\n        DateTime, default=lambda: datetime.now(timezone.utc)\n    )\n'
main_content = 'from fastapi import FastAPI\nfrom fastapi.encoders import jsonable_encoder\n\nfrom app.services.brand_scan_service import BrandScanService\nfrom app.services.product_finder import ProductFinder\nfrom app.services.product_service import ProductService\nfrom app.services.category_survey_service import CategorySurveyService\n\nfrom app.database.base import Base\nfrom app.database.database import engine\nfrom app.database import models  # noqa: F401 -- registers ProductRecord with Base.metadata\n\nfrom app.routes import dashboard, keepa, scan, analyse, opportunities_view, products\n\napp = FastAPI(title="Atlas")\n\n# Creates any tables that don\'t exist yet (e.g. product_records) without\n# touching existing ones. The old \'products\' table (incompatible legacy\n# schema) is left alone -- product_records is a separate table.\nBase.metadata.create_all(bind=engine)\n\n# NOTE: routes/add_product.py is still NOT registered -- it targets the\n# old incompatible \'products\' table. Manual add-a-product isn\'t wired\n# up yet; only scan-based persistence via product_records is.\napp.include_router(dashboard.router)\napp.include_router(keepa.router)\napp.include_router(scan.router)\napp.include_router(analyse.router)\napp.include_router(opportunities_view.router)\napp.include_router(products.router)\n\n\n@app.get("/opportunities/{brand}")\ndef opportunities_for_brand(brand: str, limit: int = 20):\n    """\n    Full A2A pipeline: find a brand\'s ASINs, price them across UK/DE/FR/ES/IT,\n    apply fees, score with OpportunityEngine, and return ranked opportunities.\n    """\n    scanner = BrandScanService()\n    return scanner.scan(brand, limit=limit)\n\n\n@app.get("/categories/{brand}")\ndef categories_for_brand(brand: str, limit: int = 100):\n    """\n    Cheap survey of what categories a brand\'s catalog spans, using\n    only UK lookups (1x token cost per ASIN, not 5x). Use this to\n    decide what to add to app/config/exclusions.py BEFORE running\n    full /opportunities scans.\n    """\n    survey = CategorySurveyService()\n    return survey.survey(brand, limit=limit)\n\n\n@app.get("/debug/{brand}")\ndef debug_brand(brand: str):\n    """\n    Returns the raw Keepa product in a JSON-safe format.\n    """\n\n    finder = ProductFinder()\n    service = ProductService()\n\n    asins = finder.find_brand(brand)\n\n    if not asins:\n        return {"error": "No products found"}\n\n    products = service.get_products([asins[0]], "UK")\n\n    if not products:\n        return {"error": "No Keepa product returned"}\n\n    return jsonable_encoder(products[0])\n'

with open("app/database/models.py", "w", encoding="utf-8") as f:
    f.write(models_content)

with open("app/main.py", "w", encoding="utf-8") as f:
    f.write(main_content)

print("Done -- app/database/models.py and app/main.py have been written.")